"""Pure physical-edit domain operations."""

from .exact_span import (
    BoundaryProof,
    CandidatePairLimitError,
    CanonicalExactAvSpanCompiler,
    ClockMapOutcome,
    DialogueIntegrityProof,
    ExactAvSpanPolicy,
    ExactAvSpanRequest,
    ExactAvSpanResult,
    ExactSpanCompiler,
    ExactSpanError,
    ExactSpanValidationError,
    FixtureBeatInput,
    NoLegalSpanError,
    SpanSelectionPolicy,
    VideoClockRange,
    VideoToAudioClockMapCertificate,
    VideoToAudioMapSegment,
    compile_exact_av_span,
    select_exact_span,
)

__all__ = [
    "BoundaryProof",
    "CandidatePairLimitError",
    "CanonicalExactAvSpanCompiler",
    "ClockMapOutcome",
    "DialogueIntegrityProof",
    "ExactAvSpanPolicy",
    "ExactAvSpanRequest",
    "ExactAvSpanResult",
    "ExactSpanCompiler",
    "ExactSpanError",
    "ExactSpanValidationError",
    "FixtureBeatInput",
    "NoLegalSpanError",
    "SpanSelectionPolicy",
    "VideoClockRange",
    "VideoToAudioClockMapCertificate",
    "VideoToAudioMapSegment",
    "compile_exact_av_span",
    "select_exact_span",
]
