"""StoryApprovalTool — 人工/Auto 审批节点 (HUMAN NODE)。

Wraps ApprovalStage as a Tool.  In interactive mode, the orchestrator
pauses here for human approval of preflight results.  In auto mode,
decisions are auto-generated.

This is a HUMAN REVIEW node — human_review = True.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from auto_cut_bot.agent.tools.base import Tool, ToolResult, tool_parameters
from auto_cut_bot.agent.tools.context import ToolContext
from auto_cut_bot.pipeline.state import mark_stage_complete


@tool_parameters({
    "type": "object",
    "properties": {
        "job_root": {
            "type": "string",
            "description": "Root directory for the pipeline job (absolute path).",
        },
        "decisions": {
            "type": "array",
            "description": "List of approval decisions. Each item: {item_id, decision, comment}.",
            "items": {
                "type": "object",
                "properties": {
                    "item_id": {
                        "type": "string",
                        "description": "Story ID to approve or reject.",
                    },
                    "decision": {
                        "type": "string",
                        "enum": ["accepted", "rejected"],
                        "description": "Approval decision.",
                    },
                    "comment": {
                        "type": "string",
                        "description": "Optional review comment.",
                    },
                },
                "required": ["item_id", "decision"],
            },
        },
        "mode": {
            "type": "string",
            "enum": ["interactive", "auto"],
            "description": "Approval mode: 'interactive' for human review, 'auto' for automated decisions.",
            "default": "interactive",
        },
    },
    "required": ["job_root"],
})
class StoryApprovalTool(Tool):
    """Tool for the human approval gate in the story generation pipeline.

    Interactive mode: the orchestrator pauses here.  The human reviewer
    provides structured decisions (accepted/rejected) for each story
    based on the preflight report.  Produces story-approval.json.

    Auto mode: decisions are auto-generated by the pipeline orchestrator.
    """
    _scopes = {"subagent"}


    human_review = True

    @property
    def name(self) -> str:
        return "story_approval"

    @property
    def description(self) -> str:
        return (
            "HUMAN REVIEW NODE: Approve or reject story proposals based on "
            "preflight feasibility reports. Interactive mode requires human "
            "decisions for each story. Produces story-approval.json."
        )

    @property
    def read_only(self) -> bool:
        return False

    @property
    def exclusive(self) -> bool:
        return True

    async def execute(self, **kwargs: Any) -> Any:
        """Execute the story_approval stage.

        In interactive mode, validates and applies the provided decisions.
        In auto mode, returns the current preflight state for auto-decision.
        """
        from autocut_core import PipelineConfig, ArtifactBus
        from auto_cut_bot.pipeline.plugins.ac_story_generation.stages.story_approval.stage import (
            ApprovalStage,
        )

        job_root = Path(kwargs["job_root"]).expanduser().resolve()
        if not job_root.is_dir():
            return ToolResult.error(f"job_root does not exist: {job_root}")

        preflight_path = job_root / "story-preflight.json"
        if not preflight_path.is_file():
            return ToolResult.error(
                f"story-preflight.json not found at {preflight_path}. "
                "Run story_preflight first."
            )

        mode = kwargs.get("mode", "interactive")
        decisions = kwargs.get("decisions", [])

        if mode == "interactive" and not decisions:
            return ToolResult(
                "story_approval is a HUMAN REVIEW node.\n\n"
                "The preflight report is ready for review.  Please provide "
                "approval decisions as a list of {item_id, decision, comment} "
                "objects, where decision is 'accepted' or 'rejected'.\n\n"
                f"Preflight report: {preflight_path}"
            )

        cfg = PipelineConfig(
            job_root=job_root,
            backend="qwen",
            mode=mode,
            extra={},
        )

        bus = ArtifactBus()
        bus.put("story_preflight", {"path": str(preflight_path)}, stage="story_preflight")

        if mode == "interactive" and decisions:
            bus.put(
                "story_approval_approval",
                {
                    "decisions": decisions,
                    "approved_at": "",
                    "approved_by": "interactive",
                },
                stage="story_approval",
            )

        stage = ApprovalStage()
        stage.config = cfg

        try:
            tasks = stage.prepare(bus)
            artifacts = stage.execute(bus, tasks)
            paths = {a.name: str(a.path) for a in artifacts}

            mark_stage_complete(None, self.name, paths)

            accepted_count = len([d for d in decisions if d.get("decision") == "accepted"])
            return ToolResult(
                "story_approval completed successfully.\n\n"
                f"Accepted: {accepted_count} stories\n"
                f"Rejected: {len(decisions) - accepted_count} stories\n"
                f"Artifacts:\n- story_approval: {paths.get('story_approval', 'N/A')}"
            )
        except Exception as exc:
            return ToolResult.error(f"story_approval failed: {exc}")