"""StoryQCReviewTool — QC 结果评审节点 (HUMAN NODE)。

Wraps QCReviewStage as a Tool.  Classifies QC reports as approved,
review, or blocked, and decides which stories proceed to rendering.

This is a HUMAN REVIEW node — human_review = True.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from auto_cut_bot.agent.tools.base import Tool, ToolResult, tool_parameters
from auto_cut_bot.agent.tools.context import ToolContext
from auto_cut_bot.pipeline.state import mark_stage_complete


@tool_parameters({
    "type": "object",
    "properties": {
        "job_root": {
            "type": "string",
            "description": "Root directory for the pipeline job (absolute path).",
        },
        "mode": {
            "type": "string",
            "enum": ["interactive", "auto"],
            "description": "Review mode: 'interactive' for human review, 'auto' for automated decisions.",
            "default": "interactive",
        },
        "decisions": {
            "type": "array",
            "description": "List of QC review decisions. Each item: {story_id, decision, comment}.",
            "items": {
                "type": "object",
                "properties": {
                    "story_id": {
                        "type": "string",
                        "description": "Story ID to approve or reject for rendering.",
                    },
                    "decision": {
                        "type": "string",
                        "enum": ["approved", "review", "blocked", "dropped"],
                        "description": "Review decision: 'approved' proceeds to render, 'blocked' needs fixes, 'dropped' is discarded.",
                    },
                    "comment": {
                        "type": "string",
                        "description": "Optional review comment.",
                    },
                },
                "required": ["story_id", "decision"],
            },
        },
    },
    "required": ["job_root"],
})
class StoryQCReviewTool(Tool):
    """Tool for the QC review human gate.

    Interactive mode: the orchestrator pauses here.  The human reviewer
    classifies each story's QC report as approved, needs review, or blocked.
    Auto mode: decisions are auto-generated by the pipeline orchestrator.

    Only 'approved' stories proceed to the rendering stage.
    """

    human_review = True

    @property
    def name(self) -> str:
        return "story_qc_review"

    @property
    def description(self) -> str:
        return (
            "HUMAN REVIEW NODE: Review QC reports for each story and decide "
            "which stories proceed to rendering. Decisions: approved, review, "
            "blocked, or dropped. Only 'approved' stories continue to render."
        )

    @property
    def read_only(self) -> bool:
        return False

    @property
    def exclusive(self) -> bool:
        return True

    async def execute(self, **kwargs: Any) -> Any:
        """Execute the story_qc_review stage.

        In interactive mode, validates and applies the provided review
        decisions. In auto mode, runs auto_process_qc_report.
        """
        from autocut_core import PipelineConfig, ArtifactBus
        from auto_cut_bot.pipeline.plugins.ac_qc.stages.qc_review.stage import (
            QCReviewStage,
        )

        job_root = Path(kwargs["job_root"]).expanduser().resolve()
        if not job_root.is_dir():
            return ToolResult.error(f"job_root does not exist: {job_root}")

        qc_index = job_root / "story-qc" / "index.json"
        if not qc_index.is_file():
            return ToolResult.error(
                f"story-qc/index.json not found at {qc_index}. "
                "Run story_qc first."
            )

        mode = kwargs.get("mode", "interactive")

        if mode == "interactive":
            return ToolResult(
                "story_qc_review is a HUMAN REVIEW node.\n\n"
                "QC reports are ready for review.  Please provide review "
                "decisions as a list of {story_id, decision, comment} objects, "
                "where decision is 'approved', 'review', 'blocked', or 'dropped'.\n\n"
                f"QC index: {qc_index}"
            )

        cfg = PipelineConfig(
            job_root=job_root,
            backend="qwen",
            mode=mode,
            extra={},
        )

        bus = ArtifactBus()
        bus.put("story_qc", {"path": str(qc_index)}, stage="story_qc")

        stage = QCReviewStage()
        stage.config = cfg

        try:
            tasks = stage.prepare(bus)
            artifacts = stage.execute(bus, tasks)
            paths = {a.name: str(a.path) for a in artifacts}

            mark_stage_complete(None, self.name, paths)

            return ToolResult(
                "story_qc_review completed successfully.\n\n"
                f"Artifacts:\n- story_qc_review: {paths.get('story_qc_review', 'N/A')}"
            )
        except Exception as exc:
            return ToolResult.error(f"story_qc_review failed: {exc}")