"""StoryPlansQCAdmissionTool — QC 准入审批节点 (HUMAN NODE)。

Wraps QCAdmissionStage as a Tool.  In interactive mode, the orchestrator
pauses here for human approval of QC admission.  In auto mode,
decisions are auto-generated.

This is a HUMAN REVIEW node — human_review = True.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from auto_cut_bot.agent.tools.base import Tool, ToolResult, tool_parameters
from auto_cut_bot.agent.tools.context import ToolContext
from auto_cut_bot.agent.runtime.state import mark_stage_complete


@tool_parameters({
    "type": "object",
    "properties": {
        "job_root": {
            "type": "string",
            "description": "Root directory for the pipeline job (absolute path).",
        },
        "decisions": {
            "type": "array",
            "description": "List of QC admission decisions. Each item: {item_id, decision, comment}.",
            "items": {
                "type": "object",
                "properties": {
                    "item_id": {
                        "type": "string",
                        "description": "Plan ID to admit to QC or reject.",
                    },
                    "decision": {
                        "type": "string",
                        "enum": ["accepted", "rejected"],
                        "description": "QC admission decision.",
                    },
                    "comment": {
                        "type": "string",
                        "description": "Optional review comment.",
                    },
                },
                "required": ["item_id", "decision"],
            },
        },
        "mode": {
            "type": "string",
            "enum": ["interactive", "auto"],
            "description": "Approval mode: 'interactive' for human review, 'auto' for automated decisions.",
            "default": "interactive",
        },
    },
    "required": ["job_root"],
})
class StoryPlansQCAdmissionTool(Tool):
    """Tool for the QC admission human approval gate.

    Interactive mode: the orchestrator pauses here.  The human reviewer
    provides structured decisions (accepted/rejected) for each plan
    based on the materialized plan index.  Produces story_plans_qc_admission.json.

    Auto mode: decisions are auto-generated by the pipeline orchestrator.
    """
    _scopes = {"subagent"}


    human_review = True

    @property
    def name(self) -> str:
        return "story_plans_qc_admission"

    @property
    def description(self) -> str:
        return (
            "HUMAN REVIEW NODE: Approve or reject plan admission to QC based on "
            "materialized plan index. Interactive mode requires human "
            "decisions for each plan. Produces story_plans_qc_admission.json."
        )

    @property
    def read_only(self) -> bool:
        return False

    @property
    def exclusive(self) -> bool:
        return True

    async def execute(self, **kwargs: Any) -> Any:
        """Execute the story_plans_qc_admission stage.

        In interactive mode, validates and applies the provided decisions.
        In auto mode, returns the current materialized plan state for auto-decision.
        """
        from autocut_core import PipelineConfig, ArtifactBus
        from autocut_core.stages.ac_qc.qc_admission.stage import (
            QCAdmissionStage,
        )

        job_root = Path(kwargs["job_root"]).expanduser().resolve()
        if not job_root.is_dir():
            return ToolResult.error(f"job_root does not exist: {job_root}")

        plans_index_path = job_root / "story-plans" / "index.json"
        if not plans_index_path.is_file():
            return ToolResult.error(
                f"story-plans/index.json not found at {plans_index_path}. "
                "Run story_plans_materialize first."
            )

        mode = kwargs.get("mode", "interactive")
        decisions = kwargs.get("decisions", [])

        if mode == "interactive" and not decisions:
            return ToolResult(
                "story_plans_qc_admission is a HUMAN REVIEW node.\n\n"
                "The materialized plan index is ready for review.  Please provide "
                "QC admission decisions as a list of {item_id, decision, comment} "
                "objects, where decision is 'accepted' or 'rejected'.\n\n"
                f"Plans index: {plans_index_path}"
            )

        cfg = PipelineConfig(
            job_root=job_root,
            backend="qwen",
            mode=mode,
            extra={},
        )

        bus = ArtifactBus()
        bus.put(
            "story_plans_materialized",
            {"path": str(plans_index_path)},
            stage="story_plans_materialize",
        )

        if mode == "interactive" and decisions:
            bus.put(
                "story_plans_qc_admission_approval",
                {
                    "decisions": decisions,
                    "approved_at": "",
                    "approved_by": "interactive",
                },
                stage="story_plans_qc_admission",
            )

        stage = QCAdmissionStage()
        stage.config = cfg

        try:
            tasks = stage.prepare(bus)
            artifacts = stage.execute(bus, tasks)
            paths = {a.name: str(a.path) for a in artifacts}

            mark_stage_complete(None, self.name, paths)

            accepted_count = len([d for d in decisions if d.get("decision") == "accepted"])
            return ToolResult(
                "story_plans_qc_admission completed successfully.\n\n"
                f"Accepted: {accepted_count} plans\n"
                f"Rejected: {len(decisions) - accepted_count} plans\n"
                f"Artifacts:\n- story_plans_qc_admission: {paths.get('story_plans_qc_admission', 'N/A')}"
            )
        except Exception as exc:
            return ToolResult.error(f"story_plans_qc_admission failed: {exc}")