"""Durable semantic persistence for the local Pipeline MVP."""

from typing import TYPE_CHECKING

from .errors import (
    BlobIntegrityError,
    BlobUnavailableError,
    CommandStateError,
    GenerationAttemptStateError,
    IdempotencyConflictError,
    JobProfileMismatchError,
    MediaEvidenceIntegrityError,
    MediaEvidenceUnavailableError,
    MediaOutputsIntegrityError,
    MediaOutputsUnavailableError,
    PersistenceConflictError,
    RecipeIntegrityError,
    RecipeUnavailableError,
    RuntimeCalibrationIdentityMismatchError,
    RuntimeStoreError,
    SemanticInputIntegrityError,
    SemanticInputUnavailableError,
    StaleHeadError,
    StoreConcurrencyError,
    StoreValidationError,
)
from .models import (
    SHADOW_CALIBRATION_MEASUREMENT_COMMAND_NAME,
    SHADOW_CALIBRATION_MEASUREMENT_PROTOCOL,
    SHADOW_LOCAL_CALIBRATION_MEASUREMENT_COMMAND_NAME,
    SHADOW_LOCAL_CALIBRATION_MEASUREMENT_PROTOCOL,
    SHADOW_LOCAL_CALIBRATION_TERMINAL_DENIAL_CODES,
    VLM_BATCH_FINALIZER_COMMAND_NAME,
    VLM_BATCH_FINALIZER_STRATEGY_VERSION,
    VLM_BATCH_IDEMPOTENCY_PREFIX,
    ArtifactMember,
    ArtifactScope,
    BlobRef,
    CalibrationValidationBinding,
    CommandClaim,
    CommandExecutionKind,
    CommandOutcome,
    CommandRejection,
    CommandSuccess,
    CommittedArtifactMemberReference,
    CommittedSemanticInputs,
    CommittedSemanticInputsRequest,
    CommittedVlmInputReference,
    CommittedVlmSemanticInput,
    GenerationAttempt,
    GenerationAttemptState,
    GenerationFailureDisposition,
    Job,
    MediaEvidenceReference,
    PersistedCalibrationRecordAnchor,
    PersistedCommittedArtifactMember,
    PersistedMediaEvidence,
    PersistedMediaOutputs,
    PersistedRecipe,
    PersistedShadowCalibrationMeasurement,
    PersistedVlmGenerationChild,
    PersistedVlmSemanticPack,
    PersistedWholeSeriesSourceManifest,
    RecipeReference,
    ShadowLocalMeasurementAttempt,
    ShadowLocalMeasurementAttemptState,
    ShadowLocalMeasurementMember,
    ShadowLocalMeasurementMemberLease,
    ShadowLocalMeasurementMemberPlan,
    ShadowLocalMeasurementMemberState,
    ShadowLocalMeasurementNotStartedProof,
    ShadowLocalMeasurementPlan,
    ShadowLocalMeasurementRecoveryLease,
    ShadowLocalMeasurementRetryAuthorization,
    ShadowLocalMeasurementStagedResponse,
    ShadowLocalMeasurementTerminalDenialRequest,
    ShadowLocalMeasurementTerminalDenialResult,
    ShadowMeasurementAttempt,
    ShadowMeasurementAttemptState,
    ShadowMeasurementMember,
    ShadowMeasurementMemberLease,
    ShadowMeasurementMemberPlan,
    ShadowMeasurementMemberState,
    ShadowMeasurementPlan,
    ShadowMeasurementRecoveryLease,
    ShadowMeasurementRetryAuthorization,
    ShadowMeasurementStagedResponse,
    ShadowMeasurementTerminalDenialRequest,
    ShadowMeasurementTerminalDenialResult,
    SourceWindowIdentity,
    VlmBatchRequestPolicy,
    VlmRequestRecordReference,
    VlmSemanticPackReference,
    VlmSemanticPackSetChild,
    WholeSeriesSourceManifestReference,
)
from .source_reuse import (
    SOURCE_REUSE_BINDING_ARTIFACT_TYPE,
    SOURCE_REUSE_BINDING_LOGICAL_ID,
    SOURCE_REUSE_BINDING_SCHEMA_VERSION,
    SOURCE_REUSE_COMMAND_NAME,
    SourceReuseBinding,
)

if TYPE_CHECKING:
    from .postgres import PostgresRuntimeStore


def __getattr__(name: str) -> object:
    """Delay the PostgreSQL adapter to keep authority-model imports acyclic."""

    if name == "PostgresRuntimeStore":
        from .postgres import PostgresRuntimeStore

        return PostgresRuntimeStore
    raise AttributeError(name)

__all__ = [
    "ArtifactMember",
    "ArtifactScope",
    "BlobIntegrityError",
    "BlobRef",
    "BlobUnavailableError",
    "CalibrationValidationBinding",
    "CommandClaim",
    "CommandExecutionKind",
    "CommandOutcome",
    "CommandRejection",
    "CommandStateError",
    "CommandSuccess",
    "CommittedArtifactMemberReference",
    "CommittedSemanticInputs",
    "CommittedSemanticInputsRequest",
    "CommittedVlmInputReference",
    "CommittedVlmSemanticInput",
    "GenerationAttempt",
    "GenerationFailureDisposition",
    "GenerationAttemptState",
    "GenerationAttemptStateError",
    "IdempotencyConflictError",
    "Job",
    "JobProfileMismatchError",
    "MediaEvidenceIntegrityError",
    "MediaEvidenceReference",
    "MediaEvidenceUnavailableError",
    "MediaOutputsIntegrityError",
    "MediaOutputsUnavailableError",
    "PersistenceConflictError",
    "PostgresRuntimeStore",
    "PersistedCalibrationRecordAnchor",
    "PersistedMediaEvidence",
    "PersistedCommittedArtifactMember",
    "PersistedMediaOutputs",
    "PersistedRecipe",
    "PersistedShadowCalibrationMeasurement",
    "PersistedVlmGenerationChild",
    "PersistedVlmSemanticPack",
    "PersistedWholeSeriesSourceManifest",
    "RecipeIntegrityError",
    "RecipeReference",
    "RecipeUnavailableError",
    "RuntimeStoreError",
    "RuntimeCalibrationIdentityMismatchError",
    "SemanticInputIntegrityError",
    "SemanticInputUnavailableError",
    "StaleHeadError",
    "StoreConcurrencyError",
    "StoreValidationError",
    "SourceWindowIdentity",
    "SHADOW_CALIBRATION_MEASUREMENT_COMMAND_NAME",
    "SHADOW_CALIBRATION_MEASUREMENT_PROTOCOL",
    "SHADOW_LOCAL_CALIBRATION_MEASUREMENT_COMMAND_NAME",
    "SHADOW_LOCAL_CALIBRATION_MEASUREMENT_PROTOCOL",
    "SHADOW_LOCAL_CALIBRATION_TERMINAL_DENIAL_CODES",
    "ShadowMeasurementAttempt",
    "ShadowMeasurementAttemptState",
    "ShadowMeasurementMember",
    "ShadowMeasurementMemberLease",
    "ShadowMeasurementMemberPlan",
    "ShadowMeasurementMemberState",
    "ShadowMeasurementPlan",
    "ShadowMeasurementRecoveryLease",
    "ShadowMeasurementRetryAuthorization",
    "ShadowMeasurementStagedResponse",
    "ShadowMeasurementTerminalDenialRequest",
    "ShadowMeasurementTerminalDenialResult",
    "ShadowLocalMeasurementAttempt",
    "ShadowLocalMeasurementAttemptState",
    "ShadowLocalMeasurementMember",
    "ShadowLocalMeasurementMemberLease",
    "ShadowLocalMeasurementMemberPlan",
    "ShadowLocalMeasurementMemberState",
    "ShadowLocalMeasurementNotStartedProof",
    "ShadowLocalMeasurementPlan",
    "ShadowLocalMeasurementRecoveryLease",
    "ShadowLocalMeasurementRetryAuthorization",
    "ShadowLocalMeasurementStagedResponse",
    "ShadowLocalMeasurementTerminalDenialRequest",
    "ShadowLocalMeasurementTerminalDenialResult",
    "VLM_BATCH_FINALIZER_COMMAND_NAME",
    "VLM_BATCH_FINALIZER_STRATEGY_VERSION",
    "VLM_BATCH_IDEMPOTENCY_PREFIX",
    "VlmBatchRequestPolicy",
    "VlmSemanticPackSetChild",
    "VlmSemanticPackReference",
    "WholeSeriesSourceManifestReference",
    "SOURCE_REUSE_BINDING_ARTIFACT_TYPE",
    "SOURCE_REUSE_BINDING_LOGICAL_ID",
    "SOURCE_REUSE_BINDING_SCHEMA_VERSION",
    "SOURCE_REUSE_COMMAND_NAME",
    "SourceReuseBinding",
    "VlmRequestRecordReference",
]
